language: node_js
node_js:
- '8'

script:
- yarn test:cov
- yarn build

deploy:
  provider: npm
  email: rolandjitsu@gmail.com
  api_key:
    secure: Gt1dqai5F5G6cfRauHF2ZtvorU64didCyq7O0a+/m1Zvr+DOTUSV+nCxhJpeHwqA99IBI/qH68Lxq6+dLBnFixVQuA3N+KoB7CsRqOQsP+3OcfzhKeO7r5+ao7ycmaqCYlXiPMbsYRhCGVkmjNcFHRnzJNmMBsJh/1Z+A8IMyS88AKaT7o6wyjy5XOwZIEGQZ4VyCd3XlvSeH9vTqw8UmzQ+hee0eSmIPY65EGBvBdSiMzRYPvUwosWFg0mexKytjDwfMnEzNGZAHmRSXMyBXaX4l9B53VprTRng9/3PsEr6qEGmiWEeaxXYhWrZYl2sRhGa+1O/klp2qvsfiSR94tkFnfHoX2MxHfyyohLTv4PMLnOR9FJuBF5opmWe6FqW3tZ7gavgI5Gc+N9RY4Z9i2SaRt+mFZwISio0egKKk9dHt4++iQRK7TV8k3LJWbYAMH4LazT+Wsgy1WoWH+PHyqTq4ayKYkrNCU1g2Q+RJS9SrOO15bfkesss2iPCUx2Hx0WLoSGYzfzkga5Qii22sXfeVAdmt/XF18ec+g1kG9Dv15lT/mQLSnkADUhH8+lz0UB/XKXHdVyGeINAUxJRSRFk+ONjq6802gyU4fQRyPghhp68vQ+sMObKKBRUwfoznwMMxaGB1DJXtBC3i0Wqi21hzqcourkpTYOnVaH1Jx4=
  on:
    tags: true

notifications:
  email:
    on_success: change
